### ISSUE TITLE
Potential Bug: Not using hidden state in Q target

### ISSUE THREAD

**Issue by sai-prasanna** [glambrechts/belief-rnn#1]
Hi, I noticed that you only passed the next sequence of observations in calculating the Q value with the target network. Shouldn't we encode the trajectory till that timestep and pass the hidden state and the next observation to compute the Q of next t+1?

https://github.com/glambrechts/belief-rnn/blob/5ca271aab711429d9db1242a99e892ef1135adec/agents/drqn.py#L179

**Comment by glambrechts** [comment]
Hi Sai, sorry but I am not sure to understand what would be wrong here, we have `(seq_bef, a, r, o, d, seq_aft)` that corresponds to $(h, a, r, o', d', h')$, with $h' = (h, a, o')$. And then I compute the target as in DRQN with $r + \gamma \max_{a' \in \mathcal{A}} Q(h', a')$. Am I doing something different in the code?

**Comment by sai-prasanna** [comment]
Yep, your implementation is perfect. I had edited some stuff and wrongly thought it was a problem in yours. Your computation of seq_aft is accurate!
